server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/repository_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  freemarker:
    settings:
      number_format: 0.##
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis666

project:
  url: http://127.0.0.1:8080
  pictureUrl : http://127.0.0.1:8088/resource/
  picturePath: /Users/schuyler/Desktop/resource
  #url: http://www.schuyler-cai.com
  #pictureUrl: http://www.schuyler-cai.com/resource/
  #picturePath: /usr/MyProject/resource
  #url: http//123.hnyinshuo.com
  #pictureUrl: http//123.hnyinshuo.com/resource/
  #picturePath: /usr/MyProject/resource